### ISSUE TITLE
Check all namespaces

### ISSUE THREAD

**Issue by sbkg0002** [robertlestak/cert-manager-sync#2]
Hi!
Currently the `SECRETS_NAMESPACE` needs to be set to a single ns. Is is possible to verify all namespaces?

Ofcourse it needs a clusterrolebinding to work, but that's easy to fix.

Thanks!

**Comment by robertlestak** [comment]
if you set the `SECRETS_NAMESPACE` to an empty string it should search all namespaces, lmk if you face any issues!
